### ISSUE TITLE
Make sure that all files are served correctly

### ISSUE THREAD

**Issue by cobraz** [blanchard-norway/website#24]
After https://github.com/blanchard-norway/website/commit/55b8b72bfe7ad99c1f68477083cd1a0129ea8cf6 and https://github.com/blanchard-norway/website/commit/824549c6c69e0b347fe218bdb3a6ff2b86a63345, we can now see some of the old website being served through Vercel:

https://blanchard-no.vercel.app/how.html

We should probably establish quality assurance before rolling it out to production.

**Comment by desirekaleba** [comment]
Hi @cobraz,

I have found this repository on Upwork and would like to help you with the refactoring.

Please, let me know if you would like to work with me.

Thanks
