### ISSUE TITLE
Epic: HTML/CSS → NextJS

### ISSUE THREAD

**Issue by cobraz** [blanchard-norway/website#25]
To ensure that the information is available for everyone about why Blanchard exist along, who they are and how they work. By doing a step-by-step process, where the website is refactored to something more modern and accessible, we enable easier solutions that are more available for both technical and non-technical people. We hope to make this website more available, therefore more active, therefore more information is spread and improvements are made.

To motivate us during this process, we've split this project into three milestones (or deliverables) in a prioritized order.

1. [Move to NextJS-based setup hosted on Vercel with HTML-based site](https://github.com/blanchard-norway/website/milestone/1)
2. [Refactor workshop events](https://github.com/blanchard-norway/website/milestone/2)
3. [Refactor all pages](https://github.com/blanchard-norway/website/milestone/3)

Our first and main task is to ensure that we can communicate our progress continuously, this is done by doing the least amount of work needed in order to move the website over to this code-base. We belive that can be done without refactoring all of the HTML/CSS code, but serving them as static files alongside our new code.

The product owner (@seacurrent) wants to be able to easily update workshop events, therefore we are prioritizing this site first. Since this is probably the first HTML page we're refactoring, it will also have its own milestone. It's nice to check that off before going all out with refactoring all of them.

#### Release planning

- [x] Demo the site after 1st milestone to @seacurrent
- [x] Move DNS on blanchard.no to Vercel (Add domain?)
- [x] Ship it 🚀

**Comment by desirekaleba** [comment]
Hi @seacurrent,

I came across this job on Upwork and would like to work with you.

Please, let me know if you would like to work with me on this.

Thanks

**Comment by cobraz** [comment]
This is done for now!
